CONFIG_KEY = "qualibrate_runner"
DEFAULT_QUALIBRATE_RUNNER_CONFIG_FILENAME = "qualibrate-runner.toml"
CONFIG_PATH_ENV_NAME = "QUALIBRATE_RUNNER_CONFIG_FILE"

Q_RUNNER_SETTINGS_ENV_PREFIX = "QUALIBRATE_APP_"
