name: Format; lint; type; tests
on:
  pull_request

jobs:
  backend-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install poetry
        run: pipx install poetry

      - uses: actions/setup-python@v5
        with:
          python-version: "3.9"
          cache: "poetry"
          cache-dependency-path: poetry.lock

      - name: Install python deps
        run: poetry install --with dev --with test
        working-directory: backend

      - name: Check python package typing
        run: poetry run poe type
        working-directory: backend

      - name: Lint python package
        run: poetry run poe lint
        working-directory: backend

      - name: Check format python package
        run: poetry run poe format
        working-directory: backend
